### ISSUE TITLE
Is master branch safe to be used in production ?

### ISSUE THREAD

**Issue by menardorama** [instipod/DuoUniversalKeycloakAuthenticator#13]
Hi,

We are using the latest release (september 2022) in production, for now it seems to be working except that only one duo config seems to be supported per realm (aka you can't have multiple auth flow using different integration key).

From what I see, latest commits seems really interesting especially group filtering (we are using role filtering actually).

So do you plan to publish a new stable version or it's safe to build from the master branch ?

Thanks

**Comment by instipod** [comment]
Several people I know are using this extension in production.  Most users are building from source as it is pretty easy with Maven.  I can publish a new pre-built if that is helpful.

Multiple Duo integration keys have been supported for awhile.  See step 6 of the README for how to use different keys for different Keycloak clients in the same flow.
