### ISSUE TITLE
Invalid redirect URI

### ISSUE THREAD

**Issue by richhoude** [instipod/DuoUniversalKeycloakAuthenticator#16]
I am getting an error": "invalid_grant", "error_description": "Invalid redirect URI https://{My IP and Port}/realms/{My realm}/login-actions/authenticate?client_id=security-admin-console&tab_id=XGWgZba-EpI'

Have you seen this before?

Thank you

**Comment by instipod** [comment]
Is this error appearing after the Duo redirect back to Keycloak or before?  Does it happen for clients other than the built-in Keycloak ones?

**Comment by richhoude** [comment]
After the redirect it happens. This is happening for both built-in keycloak Keycloak and external clients..

**Comment by instipod** [comment]
Sorry for the extended delay in my response.  I just tested this morning with a fresh install of Keycloak 22.0.1 (docker quarkus) and release 1.0.6 of the authenticator and was able to login fine with the built-in "account console" client.  

Based on the error in your initial report, do you have your redirect urls set correctly under the client in Keycloak (mainly hostname and port)?

**Comment by Nihal987** [comment]
Hi @instipod 
I am getting the same error and I believe it's because we are missing some steps in the configuration. What I'm unclear of is:
1. Which client's ID are you entering the Client ID field for the Duo Authenticator? Is it the client ID of the `account console ` client or the `security-admin-console` client or something else for the Browser auth flow?

2. Are you specifying something in the Redirect URL for this client? I assumed that because the default value for the redirect URL was * anything would work.

**Comment by Nihal987** [comment]
Actually on further investigating, I believe the error is originating from the `duoClient.healthCheck();` command.
Were there any steps you performed on your Duo Admin console aside creating a Web SDK and copying the api-hostname, client ID and secret key?

**Comment by richhoude** [comment]
I do have the redirect uri set. Sorry for late response. And please share more of your configuration

**Comment by instipod** [comment]
I didn't change any settings outside of the authenticator settings and the settings required by Keycloak to have a custom flow.  Here is my testing workflow:

- Duplicate the default browser flow
- Remove built-in keycloak 2FA subflows
- Add the Duo Universal authentication extension after username and password
- Navigate to Duo Admin, create a new Web SDK client, copy the Integration Key, Secret Key, and API hostname from Duo Admin.  Make sure you have Duo Universal enabled on your Duo account, and for the Web SDK entry (I'm not sure if you have to do this anymore, Duo may default to this enabled now)
- Input the values into the Duo Universal authenticator settings and well as an alias (i.e. duo-1 or similar)
- Set the duplicated flow to be the default browser flow
- In an incognito or private window, navigate to the Keycloak Account Portal (http://localhost:8080/realms/master/account) and attempt to login
