### ISSUE TITLE
Authentication against Duo failed 

### ISSUE THREAD

**Issue by syscoder911** [instipod/DuoUniversalKeycloakAuthenticator#18]
2023-10-18 12:56:26,813 WARN  [com.instipod.duouniversal.DuoUniversalAuthenticator] (executor-thread-28) Authentication against Duo failed with exception: com.duosecurity.exception.DuoException: invalid_client

**Comment by instipod** [comment]
invalid_client points to a configuration error with the Duo information.  Have you verified your client_id (integration key) and secret match what is shown in your Duo console?

**Comment by syscoder911** [comment]
Yes, the client_id and secret match what is shown in my Duo console, but I don't know why I'm getting this error. Additionally, I'm not seeing any activities on the Web SDK application in my Duo console.

![image](https://github.com/instipod/DuoUniversalKeycloakAuthenticator/assets/61664377/6908c7ea-17be-4aa2-b936-587b5ea1f918)

**Comment by instipod** [comment]
Do you see Application supports universal prompt and Show new universal prompt selected in the Duo Admin Console?

<img width="1044" alt="image" src="https://github.com/instipod/DuoUniversalKeycloakAuthenticator/assets/744666/753660f0-3ae5-4f5f-82f8-cf6d352b23c6">

**Comment by markus-meissner** [comment]
I've got the same problem and the solution was to use `Alias=duo` in the keycloak configuration.
