### ISSUE TITLE
Create a maven central deployment

### ISSUE THREAD

**Issue by concurrent-recursion** [instipod/DuoUniversalKeycloakAuthenticator#24]
As a user of this library and Keycloak, I would like to be able to pull the library into my project via Maven as a dependency instead of downloading the binaries from github.

I have experience with this, and I can submit a PR if you are interested for the GH workflow and pom.xml changes, but there are some steps that you would need to perform to get it approved to sonatype's maven repository

**Comment by hwo-wd** [comment]
Would be a great addition indeed; not sure whether we need sonatype's mvn repo though or if maven.pkg.github.com could do the trick as well?

**Comment by concurrent-recursion** [comment]
The github maven package manager would require the person pulling the package to have repository access to the project, and they would have to specify the github maven repo in their repositories section of their pom or gradle file.

Sonatype is the default, standard, public maven repository

**Comment by instipod** [comment]
Can you give me some more information about what steps would need to be performed to keep the extension updated on the repository?  I haven't published something to the public repository before and am unfamilar.
