### ISSUE TITLE
RedirectUrl isn't encoded

### ISSUE THREAD

**Issue by Batigoal** [instipod/DuoUniversalKeycloakAuthenticator#25]
In the method of createAuthUrl of the Client-Ojbect the query parameters are not URL-encoded!!
Especially the redirectUri, which is a security risk and doesn't work for me!

**Comment by Ansa89** [comment]
I'm not sure to correctly understand your request.
Anyway, I created instipod/DuoUniversalKeycloakAuthenticator#27 that should address it.
